version: "3.8"

x-common-variables: &common-variables
  SIS_MICROSERVICE_USUARIO: http://sis-usuario:8080
  SIS_MICROSERVICE_CAIXA: http://sis-caixa:8080

  SPRING_PROFILES_ACTIVE: "default,prod"
  SPRING_JDBC_URL: "jdbc:mysql://mysql-service:3306/sisget_prod?serverTimezone=America/Sao_Paulo"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "root"

  JWT_SECRET: tTw2sXXOc4lJn63lLAItQPu7BkBhH5E2O1u8NIMqCz1pwuR7warCqc9rDAPL6UDLLyJa6XH8L8o7s65fXmhEFhxIiC
  JWT_EXPIRATION: 86400000

  JAVA_OPTIONS: "-Duser.timezone=GMT-3"
  TZ: "America/Sao_Paulo"

services:

  traefik:
    image: traefik:v3.5.3
    command:
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.network=sisget-network"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=seu-email@dominio.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"   # dashboard
      - "8888:8888"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik-letsencrypt:/letsencrypt"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - sisget-network

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_BASE: /dozzle
    ports:
      - "8888:8080"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dozzle.rule=PathPrefix(`/dozzle`)"
        - "traefik.http.routers.dozzle.entrypoints=websecure"
        - "traefik.http.routers.dozzle.tls.certresolver=le"
        - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
    networks:
      - sisget-network

  sisget-client:
    image: dsantana87/sis-client:latest
    container_name: sisget-client
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.client.rule=PathPrefix(`/`)"
        - "traefik.http.routers.client.entrypoints=web"
        - "traefik.http.routers.client.tls=false"
        - "traefik.http.services.client.loadbalancer.server.port=80"
      replicas: 1
    networks:
      - sisget-network

  sis-gateway:
    image: dsantana87/sis-gateway:latest
    container_name: sis-gateway
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.gateway.rule=PathPrefix(`/api`)"
        - "traefik.http.routers.gateway.entrypoints=web"
        - "traefik.http.routers.gateway.tls=false"
        - "traefik.http.services.gateway.loadbalancer.server.port=8080"
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      <<: *common-variables
    networks:
      - sisget-network

  sis-auth:
    image: dsantana87/sis-auth:latest
    container_name: sis-auth
    restart: always
    environment:
      <<: *common-variables
    networks:
      - sisget-network

  sis-usuario:
    image: dsantana87/c:latest
    container_name: sis-usuario
    restart: always
    environment:
      <<: *common-variables
    networks:
      - sisget-network

networks:
  sisget-network:
    driver: overlay

volumes:
  traefik-letsencrypt:
